### ISSUE TITLE
Preview mode is broken

### ISSUE THREAD

**Issue by fredkingham** [nhsengland/NCDR-reference-library#48]

**Comment by ghickman** [comment]
Can you define broken?  Is there a particular part perhaps which isn't working as expected?

**Comment by fredkingham** [comment]
sorry, so preview mode used to show everything whether it was published or not and it used to change the colour of the header.

It would be triggered by pressing
<img width="1423" alt="screen shot 2019-02-13 at 17 33 08" src="https://user-images.githubusercontent.com/2175455/52731477-b728c800-2fb5-11e9-8065-4eb600604823.png">

and saving on preview_mode on what was previously the user profile, but should now be the user but it doesn't seem to work any more
