### ISSUE TITLE
None of the Databases have owners?

### ISSUE THREAD

**Issue by fredkingham** [nhsengland/NCDR-reference-library#53]
All of the database owners fields show the below

<img width="175" alt="screen shot 2019-02-14 at 18 59 23" src="https://user-images.githubusercontent.com/2175455/52810639-ef4e0a80-308a-11e9-925f-ccd7fe883e6b.png">

Is it because we're not pulling them through or is it not a thing any more? In which case can we remove the field from the front end?

**Comment by ghickman** [comment]
Fixed in 204e8f2
